class dataa {
  final String title;
  final String description;
  final String image;

  dataa(this.title, this.description, this.image);
}

var dataaList = [
  dataa(
    "Javascript", 
    "JavaScript, often abbreviated JS, is a programming language that is one. It was created by Brendan Eich in 1995 and is most commonly used as part of a web browser. JavaScript is a prototype-based, multi-paradigm, dynamic language, supporting object-oriented, imperative, and declarative (e.g. functional programming) styles. It has an API for working with text, arrays, dates and regular expressions, but does not include any I/O, such as networking, storage, or graphics facilities, relying for these upon the host environment in which it is embedded. JavaScript was standardized in ECMAScript (ECMA-262) in 2008 and is implemented in many web browsers. ECMA-262 also specified the standard for JavaScript object notation (JSON) and the ECMAScript Harmony Language Module from the same specification. ECMA-262 is the fifth edition of the ECMA-262 standardization process. ECMA-262 is the latest version of the standardization process for ECMAScript and is the basis for the latest versions of the ECMAScript specification and the latest versions of the ECMAScript Language Binding. ECMAScript is the basis for the latest versions of the ECMAScript specification and the latest versions of the ECMAScript Language Binding. ECMAScript is the basis for the latest versions of the ECMAScript specification and the latest versions of the ECMAScript Language Binding. ", 
    "assets/book-js.png"
    ),
    dataa(
    "CSS", 
    "CSS is a style sheet language used for describing the presentation. CSS is designed to enable the separation of presentation and content, including layout, colors, and fonts. CSS describes how HTML elements are to be displayed on screen, on paper, in print, by control software, or on other media. CSS saves a lot of work. It can control the layout of multiple web pages all at once, or individually. CSS-based websites offer many options for customizing the look and feel of a web page. CSS is useful for websites that feature both images and text. It is also useful for websites that feature primarily images, such as photo galleries, avatars, profile pictures, and so on. CSS is also useful for websites that feature primarily text, such as blogs, wikis, and comment forums. CSS is also useful for websites that feature both images and text, such as photo blogs, blogs with embedded images, and so on. CSS is also useful for websites that feature both images and text, such as photo blogs, blogs with embedded images, and so on. CSS is also useful for websites that feature both images and text, such as photo blogs, blogs with embedded images, and so on. ", 
    "assets/book-css.png"
    ),
    dataa(
    "Python", 
    "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace. It provides constructs that enable clear programming on both small and large scales. In July 2018, Van Rossum stepped down as the leader in the Python community, and in April 2019, the Python Software Foundation announced plans to move Python to the Linux foundation. Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including object-oriented, imperative, functional programming, and procedural styles. Python is often described as a batteries included language due to its comprehensive standard library. Python interpreters are available for many operating systems. CPython, the reference implementation of Python, is open source software and has a community-based development model, as do nearly all of its variant implementations. CPython is managed by the non-profit Python Software Foundation. CPython is licensed under the PSF license, and all its variants are also licensed under the PSF license.",
    "assets/book-python.png"
    ),
    dataa(
    "React Native", 
    "React Native is an open-source mobile application framework created by Facebook. It is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined to build native apps. React Native is built using the open source component model and is based on React, the open source JavaScript library. React Native is designed to work with existing iOS and Android development tools and frameworks, such as Xcode and Android Studio. React Native is a collection of small, modular pieces of code that can be combined", 
    "assets/book-rn.png"
    ),
    dataa(
    "HTML", 
    "HTML is the standard markup language for creating Web pages. HTML describes the structure of a Web page semantically and originally included cues for the appearance of the document. HTML elements are the building blocks of HTML pages. With HTML constructs, images and other objects such as interactive forms may be embedded into the rendered page. HTML provides a means to create structured documents by denoting structural semantics for text such as headings, paragraphs, lists, links, quotes and other items. HTML elements are delineated by tags, written using angle brackets. A tag is a keyword surrounded by angle brackets. HTML elements generally have a start and end tag. The start tag introduces the element, the end tag closes the element. HTML elements may contain other elements and text, including nested elements. HTML elements may also be void, that is, they may not contain any content, and may not have an end tag. The use of void elements is discouraged, however, as most browsers ignore void elements. HTML documents may contain frames. Frames are alternate presentations of the same document, for example a print-friendly version, or a version for visually impaired users. HTML frames may be used to create separate windows in a browser or a separate web page in a browser plug-in. HTML frames may contain other frames. HTML frames may be used to create separate windows in a browser or a separate web page in a browser plug-in. HTML frames may contain other frames. HTML frames may be used to create separate windows in a browser or a separate web page in a browser plug-in. HTML frames may contain other frames.", 
    "assets/book-html.png"
    ),
    dataa(
    "Flutter", 
    "Flutter is an open-source, cross-platform framework for building high-performance, high-fidelity, mobile apps with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS, Android, web, and desktop from a single codebase. Flutter is an open-source project with a focus on performance, simplicity, and fluid user interfaces. Flutter is Google’s mobile app SDK for crafting high-quality natively compiled applications for iOS", 
    "assets/book-flutter.png"
    ),
];